spring:
  application:
    name: uo-registry-service

server:
  port: 9000
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      wait-time-in-ms-sync-empty: 0

